### PR TITLE
Update for ReSharper 2018.1

### PR DESCRIPTION
**Pull request by 0x0309**

### CODE REVIEW

**Comment by vfrz** [comment]
@kendallb Exactly, you can't install extension that are not marked compatible. The only way to have it working with resharper 2018 right now is to use the 0x0309's fork.

**Comment by kendallb** [comment]
How do you install it manually from the fork?

**Comment by johnendev** [comment]
To install manually, run build.ps1 to generate the plugin package. Then in ReSharper's options you can add the folder containing the plugin package as an additional plugin source, and it will be available to install from the extension manager.

**Comment by 0x0309** [comment]
To install manually, run build.ps1. Then add the folder containing the generated nupkg to ReSharper's plugin sources. It will then be available to install from the extension manager.

**Comment by kendallb** [comment]
Thanks, I will give it a try!

**Comment by kendallb** [comment]
Ok, I am not sure what I am missing? I got 0x0309's fork and synced to the resharper-sdk-update, then ran build.ps1 from the command line with PowerShell and it build a nupkg file under the ForTea\output directory called JLebosquain.ForTea.1.11.1-resharper-sdk-up0001.nupkg. I then told Resharper to add that directory to the extensions gallery but it still does not find it when I search for it?

image

image

**Comment by johnendev** [comment]
A build off the master branch generates a package with the name ``JLebosquain.ForTea.1.11.0.nupkg``, for builds of other branches I think you need to select the ``Include prerelease packages`` option.

**Comment by kendallb** [comment]
Ahh, thanks! I just merged to the master branch on my local copy and built that. Works now!

**Comment by MrJul** [comment]
The PR is really appreciated!
However, I'm going to close it as I've already updated ForTea (with other changes such as using the SDK-based csproj file).

Thank you!

**Pull request closed without merging**
