### PR TITLE
Support of R# 2017.2

### PR DESCRIPTION
**Pull request by CzBuCHi**
please check csproj references - simple update didnt work so i wiped out all references, installed R# 2017.2 SDK and after that added missing references ... for ex. i didnt need to have any mono references to compile without errors ...

### CODE REVIEW

**Comment by remcoros** [comment]
👍 Confirmed working

**Comment by AqD** [comment]
Confirmed working on VS 2015 and VS 2017. Thanks!!!

**Comment by fnajera-rac-de** [comment]
+1 in VS 2017. Thanks!

**Comment by damageboy** [comment]
Can this please be merged and released?

**Comment by MrJul** [comment]
Sorry, had little time lately, I'll review and merge asap.

**Comment by TimSirmovics** [comment]
Any idea when this might be released?

**Comment by AqD** [comment]
@TimSirmovics: My build is here https://drive.google.com/open?id=0B4I3ZOP_BRUyNjA1YUR1dmlHdEU

You need to put it to a local folder, add that folder to list of extension source in Resharper Optins \ Environment \ Extension Manager, and then it should show up in extensions for installation.

**Comment by TimSirmovics** [comment]
Thanks I was able to install it but none of the functionality or highlighting works for me.. might be my own problem, i'm on R# 2017.2.2.

**Comment by AqD** [comment]
I'm using 2017.2.2 here. No problem. Can you see fortea installed? What happens when you open a tt or t4 file?

**Comment by TimSirmovics** [comment]
I can see ForTea 1.9.1 installed in the extension manager.
When I open a .tt or .ttinclude file it's just the same as if ForTea is not installed, there is no syntax highlighting, no code completition or R# functions.

**Comment by MrJul** [comment]
Thank you for the PR! I've implemented the missing methods and cleaned up the csproj (with PackageReference, future updates will be easier). ForTea 1.10 for ReSharper 2017.2 is now released.

**Pull request merged**
