### PR TITLE
Updated for Resharper 2016.1

### PR DESCRIPTION
**Pull request by karpach**
I briefly tested changes and those work on my local machine with Resharper 2016.1

### CODE REVIEW

**Comment by SeriousM** [comment]
I just quickly reviewed your patch and it looks promissing!
@MrJul please accept this PR and push a new package to jetbrains!

**Comment by SeriousM** [comment]
It seems this project is dead. Maybe MrJul may transfer the ownership of this project to someone who cares (@karpach, @seriousm)?

**Comment by MrJul** [comment]
Yes, I admit I don't have much time for ForTea and could use some help. The PR is appreciated.

**Comment by SeriousM** [comment]
:clap: thank you for the update! may you update the ReSharper gallery too?

**Comment by MrJul** [comment]
It's coming, just testing and doing minor changes before :)

**Comment by MrJul** [comment]
@karpach FYI, I've removed the added build.bat (there's already a build.cmd), MessageBox call and fixed some formatting. I should have commented on the PR before accepting it, but since I was (very) late in accepting this, I've fixed it myself.

**Comment by karpach** [comment]
Thank you so much. I forgot to do that clean up myself.

**Pull request merged**
