### PR TITLE
Update to 2018.2 SDK

### PR DESCRIPTION
**Pull request by matkoch**
Now targets net461. Wave version should be automatically updated to 182.

Merge as soon as you wish :)

### CODE REVIEW

**Comment by ac931274** [comment]
I have had a look at this PR and it will not work in my opinion.  There has been a massive change in the underlying API for R# between these versions and it will NOT be a simple update.

**Comment by matkoch** [comment]
@ac931274 yes this won't work. The PR was created long before the release of 2018.2 and was only to communicate the change in target framework. This is difficult to spot.

**Comment by ac931274** [comment]
I have seemingly got this to work with the latest version of R#.  There are a couple of fixes I need to resolve and a bit more testing and I will create a pull request.  Main issue is that there are a couple of new methods that need overriding from the R# side and I also need to trace a few more changes to the API.
image

**Comment by ac931274** [comment]
I have now created at pull request #99 for this fix.

**Comment by MrJul** [comment]
Obsoleted by #99

**Pull request closed without merging**
