### PR TITLE
Recognize and resolve custom MSBuild variables

### PR DESCRIPTION
**Pull request by molnarm**
(solution for #60)

Properties defined in project files are now resolved in include & assembly paths.

I also removed `TryGetVsBuildMacroInfo` in the third commit, because MSBuildExtensions also returns built-in properties so there's no reason to use two different methods, but feel free to disagree.

### CODE REVIEW

**Comment by MrJul** [comment]
Thank you for the PR!

Can you please add back `TryGetVsBuildMacroInfo`? I agree that it *shouldn't* make a difference in theory, but a quick look at VS implementation in dotPeek shows that it calls both the VS macro and MSBuild, so let's do the same for consistency.

```
private string ExpandAllVariables(string input)
{
  if (!string.IsNullOrWhiteSpace(input))
  {
	input = TextTemplatingService.ExpandEnvironmentVariables(input);
	input = this.ExpandVsMacroVariables(input); // uses IVsBuildMacroInfo
	input = this.ExpandProjectProperties(input); // uses IVsBuildPropertyStorage
  }
  return input;
}
```

**Comment by molnarm** [comment]
You are right, I reverted the last commit that removed it.

**Comment by MrJul** [comment]
Looks good, thank you!

**Comment by wigy-opensource-developer** [comment]
There are some poor people still using Resharper 8 with VS 2013. Is there a way to merge it to a 1.2 branch so the default Resharper 8 extension repo gets this fix? This is only a question, because there are features *removed* from the trunk, namely R# 8 support.

**Comment by MrJul** [comment]
@wigy-opensource-developer I's really a pain to maintain support for multiple ReSharper versions, especially for testing (plus you can't have one package for all versions anymore). I'm following JetBrains recommended way of only supporting the latest version, which should no longer be a problem with their new subscription model. I'm sorry about that.

You can fork from d6fb6012f34f518e74e8799549f62130f564efc9, cherry pick the appropriate commits from this PR and build yourself a package for ReSharper 8.

**Pull request merged**
